export interface Env {
  SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REDIRECT_URI: string;
  OAUTH_STATE_SIGNING_SECRET?: string;
  TOKEN_ENCRYPTION_KEY?: string;
  MCP_TOKEN_HASH_PEPPER?: string;
}
